public with sharing class integ_FieldTypes {
    public static final String STRINGZ = 'String';
    public static final String DECIMALZ = 'Decimal';
    public static final String INTEGERZ = 'Integer';
    public static final String BOOLEANZ = 'Boolean';
    public static final String LOOKUP = 'Lookup';
    public static final String LOOKUP_FORMULA = 'Lookup Formula';
    public static final String FORMULA = 'Formula';
}